-- Table Egg Management System - Supabase/Postgres schema
-- Run this in the Supabase SQL Editor for a fresh project database.
-- The mixed-case column names are quoted intentionally because the app's
-- SQLAlchemy models use names such as "batchId", "ageWeeks", and "createdAt".

begin;

create table if not exists public.users (
    id integer generated by default as identity primary key,
    email varchar unique,
    hashed_password varchar,
    original_password_hash varchar,
    name varchar,
    role varchar
);

create unique index if not exists ix_users_email on public.users (email);
create index if not exists ix_users_id on public.users (id);

create table if not exists public.flocks (
    id integer generated by default as identity primary key,
    "batchId" varchar,
    house varchar,
    breed varchar,
    "ageWeeks" integer,
    quantity integer,
    mortality integer default 0,
    status varchar
);

create index if not exists ix_flocks_id on public.flocks (id);

create table if not exists public.production (
    id integer generated by default as identity primary key,
    date varchar,
    "flockId" varchar,
    staff_incharge varchar,
    "eggsCollected" integer,
    large integer default 0,
    medium integer default 0,
    small integer default 0,
    jumbo integer default 0,
    extralarge integer default 0,
    peewee integer default 0,
    cracked integer default 0,
    reject integer default 0,
    bunkig integer default 0,
    "totalGoodEggs" integer default 0,
    "damagedEggs" integer,
    mortality integer,
    notes varchar,
    "createdAt" timestamp without time zone default now()
);

create index if not exists ix_production_id on public.production (id);

create table if not exists public.inventory (
    id integer generated by default as identity primary key,
    "totalSellable" integer default 0,
    "totalDamaged" integer default 0,
    large integer default 0,
    medium integer default 0,
    small integer default 0,
    jumbo integer default 0,
    extralarge integer default 0,
    peewee integer default 0
);

create index if not exists ix_inventory_id on public.inventory (id);

create table if not exists public.sales (
    id integer generated by default as identity primary key,
    customer varchar,
    customer_name varchar,
    contact_no varchar,
    address varchar,
    date varchar,
    "traysSold" integer,
    jumbo integer default 0,
    extralarge integer default 0,
    large integer default 0,
    medium integer default 0,
    small integer default 0,
    peewee integer default 0,
    "pricePerTray" double precision,
    total double precision,
    balance double precision default 0.0,
    status varchar,
    staff_incharge varchar,
    "createdAt" timestamp without time zone default now()
);

create index if not exists ix_sales_id on public.sales (id);

create table if not exists public.income (
    id integer generated by default as identity primary key,
    source varchar,
    "referenceType" varchar,
    "referenceId" integer,
    amount double precision,
    date varchar,
    category varchar,
    notes varchar
);

create index if not exists ix_income_id on public.income (id);

create table if not exists public.expenses (
    id integer generated by default as identity primary key,
    title varchar,
    category varchar,
    amount double precision,
    date varchar,
    vendor varchar,
    notes varchar
);

create index if not exists ix_expenses_id on public.expenses (id);

create table if not exists public.calendar (
    id integer generated by default as identity primary key,
    title varchar,
    date varchar,
    type varchar,
    time varchar,
    description varchar,
    status varchar default 'Pending'
);

create index if not exists ix_calendar_id on public.calendar (id);

create table if not exists public.vaccinations (
    id integer generated by default as identity primary key,
    "batchId" varchar,
    "vaccineName" varchar,
    "dateAdministered" varchar,
    "nextDueDate" varchar,
    "administeredBy" varchar,
    status varchar default 'Pending',
    notes varchar
);

create index if not exists ix_vaccinations_id on public.vaccinations (id);

create table if not exists public.hatchery (
    id integer generated by default as identity primary key,
    "batchCode" varchar,
    "eggCount" integer,
    "fertileEggCount" integer,
    "hatchedCount" integer,
    "hatchDate" varchar,
    notes varchar
);

create index if not exists ix_hatchery_id on public.hatchery (id);

create table if not exists public.staff (
    id integer generated by default as identity primary key,
    name varchar,
    role varchar,
    "contactNumber" varchar,
    email varchar,
    status varchar default 'Active'
);

create index if not exists ix_staff_id on public.staff (id);

create table if not exists public.feed_consumption (
    id integer generated by default as identity primary key,
    date varchar,
    "flockId" varchar,
    "feedConsumedKgs" double precision,
    "createdAt" timestamp without time zone default now()
);

create index if not exists ix_feed_consumption_id on public.feed_consumption (id);

-- The app uses Supabase as a private Postgres database through the FastAPI
-- backend. RLS is enabled so Supabase anon/client API access stays closed
-- unless you intentionally add policies later.
alter table public.users enable row level security;
alter table public.flocks enable row level security;
alter table public.production enable row level security;
alter table public.inventory enable row level security;
alter table public.sales enable row level security;
alter table public.income enable row level security;
alter table public.expenses enable row level security;
alter table public.calendar enable row level security;
alter table public.vaccinations enable row level security;
alter table public.hatchery enable row level security;
alter table public.staff enable row level security;
alter table public.feed_consumption enable row level security;

insert into public.inventory (
    "totalSellable",
    "totalDamaged",
    large,
    medium,
    small,
    jumbo,
    extralarge,
    peewee
)
select 0, 0, 0, 0, 0, 0, 0, 0
where not exists (select 1 from public.inventory);

insert into public.users (email, hashed_password, original_password_hash, name, role)
values
    (
        'admin@farm.com',
        '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
        '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
        'System Admin',
        'Admin'
    ),
    (
        'staff@farm.com',
        '10176e7b7b24d317acfcf8d2064cfd2f24e154f7b5a96603077d5ef813d6a6b6',
        '10176e7b7b24d317acfcf8d2064cfd2f24e154f7b5a96603077d5ef813d6a6b6',
        'Farm Worker',
        'Staff'
    )
on conflict (email) do nothing;

commit;
